name: 'dbt_artifacts_firebolt'
version: '1.0.0'
config-version: 2
require-dbt-version: ">=1.3.0"
profile: 'dbt_artifacts_firebolt'

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "logs"

# Configure hooks for dbt_artifacts
on-run-end:
  - "{{ dbt_artifacts.upload_results(results) }}"
